#### Basic Operations
- Substitution
    - Substitution replaces all instances of something in an expression with something else. 
    - It is done using the subs method
- SymPy objects are immutable. 
- That means that subs does not modify it in-place

- Converting Strings to SymPy Expressions
    - sympify function can be used to convert strings into SymPy expressions.
    - simplify --> used to simplify the equations
    - sympify  --> used to convert string to sympy expression
    - sympify uses eval. Don’t use it on unsanitized input
- evalf
- lambdify

In [1]:
from sympy import*


In [5]:
x,y,z=symbols('x y z')
print(x)
print(y)
print(z)


x
y
z


In [14]:
expre=sin(x**2)+x+1
expre.subs(x,0)

1

In [10]:
ex=x**2 + x*y + x + y + 5
ex.subs(x,2)

3*y + 11

In [13]:
ex.subs(y,1)

x**2 + 2*x + 6

In [20]:
c=cos(x**5)+y+10
d=c.subs(x,0)
d

y + 11

In [21]:
d.subs(y,1)

12

In [29]:
c=cos(x*5)+y+10
ss=c.subs(x,y)
ss

y + cos(5*y) + 10

In [31]:
ss.subs(y,9)

cos(45) + 19

In [32]:
expression=cos(x)+sin(x)+(x**2)+(y**4)+(x*y*z)+10

In [34]:
expression.subs([(x,0),(y,1),(z,5)])

12

In [36]:
x_ans=(x**4)+(x**2)+5*x+10
x_ans.subs(x,1)

17

#####  we wanted to replace all instances of x that have an even power with y,

In [41]:
expr = x**4 - 4*x**3 + 4*x**2 - 2*x + 3
replacements = [(x**i, y**i) for i in range(6) if i % 2 == 0]
print("replacements -->  ",replacements)
expr.subs(replacements)

replacements -->   [(1, 1), (x**2, y**2), (x**4, y**4)]


-4*x**3 - 2*x + y**4 + 4*y**2 + 3

#### Converting Strings to SymPy Expressions

In [42]:
string="(x**2)+2*x+3"
expression=sympify(string)
expression

x**2 + 2*x + 3

In [43]:
expression.subs(x,2)

11

In [45]:
expression.subs(x,y)

y**2 + 2*y + 3

#### evalf
- sympify uses evalf. Don’t use it on unsanitized input.
- To evaluate a numerical expression into a floating point number, use evalf

In [46]:
s=sqrt(8)
s

2*sqrt(2)

In [48]:
s.evalf()

2.82842712474619

In [49]:
expression.evalf()

x**2 + 2.0*x + 3.0

In [53]:
pi.evalf()

3.14159265358979

- SymPy can evaluate floating point expressions to arbitrary precision. By default, 15 digits of precision are used, but you can pass any number as the argument to evalf.

In [56]:
pi.evalf(5)

3.1416

In [57]:
pi.evalf(100)

3.141592653589793238462643383279502884197169399375105820974944592307816406286208998628034825342117068

- To numerically evaluate an expression with a Symbol at a point, we might use subs followed by evalf, but it is more efficient and numerically stable to pass the substitution to evalf using the subs flag, which takes a dictionary of Symbol: point pairs

In [60]:
ex=x**2+2*x+2
ex.evalf(subs={x:2.4})

12.5600000000000

In [62]:
ex=2*x+2
ex.evalf(subs={x:2.50})

7.00000000000000

In [64]:
ex=x*y+2*y+x+10
ex.evalf(subs={x:2.0})

x*y + x + 2.0*y + 10.0

In [65]:
ex=x+y+4
ex.evalf(subs={x:1.0})

x + y + 4.0

In [66]:
ex=x+2*x+3
ex.evalf(subs={x:1.0})

6.00000000000000

- there are roundoff errors smaller than the desired precision that remain after an expression is evaluated. Such numbers can be removed at the user’s discretion by setting the chop flag to True

In [69]:
one = cos(x)**2 + sin(x)**2
(one - 1).evalf()
0.e-124
(one - 1).evalf(chop=True)

sin(x)**2 + cos(x)**2 - 1.0

In [73]:
one = cos(x)**2 + sin(x)**2 + 9
one=one.subs(x,0)
(one - 1).evalf()
0.e-124
(one - 1).evalf(chop=True)

9.00000000000000

In [77]:
one = cos(x)**2 + sin(x)**2 
one=one.subs(x,45)
(one - 1).evalf()
0.e-124
(one - 1).evalf(chop=False)

-0.e-124

In [78]:
one = cos(x)**2 + sin(x)**2 
one=one.subs(x,45)
(one - 1).evalf()
0.e-124
(one - 1).evalf(chop=True)

0

In [79]:
one = cos(x)**2 + sin(x)**2 + 9
one=one.subs(x,0)
(one - 1).evalf()
0.e-124
(one - 1).evalf(chop=False)

9.00000000000000

#### lambdify
- subs and evalf are good if you want to do simple evaluation
-  but if you intend to evaluate an expression at many points, there are more efficient ways
- For example, if you wanted to evaluate an expression at a thousand points, using SymPy would be far slower than it needs to be, especially if you only care about machine precision. Instead, you should use libraries like NumPy and SciPy.

- easiest way to convert a SymPy expression to an expression that can be numerically evaluated is to use the lambdify function. lambdify acts like a lambda function, except it converts the SymPy names to the names of the given numerical library, usually NumPy.
- We can use other libraries than NumPy.

In [86]:
import numpy as np
a=np.arange(10)
ex=2*x+10

f = lambdify(x, ex, "numpy")
print(a)
f(a)

[0 1 2 3 4 5 6 7 8 9]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [90]:

a=np.arange(2,10,2)
print(a)
e=2*x+x
f=lambdify(x,e,"numpy")
f(a)

[2 4 6 8]


array([ 6, 12, 18, 24])

In [91]:

a=np.arange(2,10,2)
print(a)
e=2*x+x
f=lambdify(x,e,"math")
f(a)

[2 4 6 8]


array([ 6, 12, 18, 24])

In [96]:
e=x+2
f=lambdify(x,e,'math')
print(f(0.1))
print(f(2))
a=np.arange(5)
f(a)

2.1
4


array([2, 3, 4, 5, 6])