### Numpy basics
- Numpy version and its inbuilt functions
- multiple ways to create different dimensions arrays using numpy python
- create multiple arrays with different dimentions

In [2]:
import numpy as np
print("Numpy version is ",np.__version__)
for i in dir(np):
    print("np.",end="")
    print(i)

Numpy version is  1.16.2
np.ALLOW_THREADS
np.AxisError
np.BUFSIZE
np.CLIP
np.ComplexWarning
np.DataSource
np.ERR_CALL
np.ERR_DEFAULT
np.ERR_IGNORE
np.ERR_LOG
np.ERR_PRINT
np.ERR_RAISE
np.ERR_WARN
np.FLOATING_POINT_SUPPORT
np.FPE_DIVIDEBYZERO
np.FPE_INVALID
np.FPE_OVERFLOW
np.FPE_UNDERFLOW
np.False_
np.Inf
np.Infinity
np.MAXDIMS
np.MAY_SHARE_BOUNDS
np.MAY_SHARE_EXACT
np.MachAr
np.ModuleDeprecationWarning
np.NAN
np.NINF
np.NZERO
np.NaN
np.PINF
np.PZERO
np.RAISE
np.RankWarning
np.SHIFT_DIVIDEBYZERO
np.SHIFT_INVALID
np.SHIFT_OVERFLOW
np.SHIFT_UNDERFLOW
np.ScalarType
np.Tester
np.TooHardError
np.True_
np.UFUNC_BUFSIZE_DEFAULT
np.UFUNC_PYVALS_NAME
np.VisibleDeprecationWarning
np.WRAP
np._NoValue
np._UFUNC_API
np.__NUMPY_SETUP__
np.__all__
np.__builtins__
np.__cached__
np.__config__
np.__doc__
np.__file__
np.__git_revision__
np.__loader__
np.__mkl_version__
np.__name__
np.__package__
np.__path__
np.__spec__
np.__version__
np._add_newdoc_ufunc
np._arg
np._distributor_init
np._globals
np._mat
n

#### multiple ways to create different dimensions arrays using numpy python
- arange
    - syntex
    - numpy.arange(start,stop,step).reshape(dimension)
        - start -> starting value
        - stop ->taking values upto (stop-1)
        - step ->Nothing but increment
        - reshape -> for dimensions
- random.randint
    - It will take numbers randomly
    - syntax
    - numpy.random.randint(start,stop,size=(dimension))
- array
    - syntax
    - numpy.array([[1,2,3],[3,2,6]])
    - or 
    - numoy.array(list)
- linspace
    - returns evenly spaced numbers over a specified interval
    - syntax
    - numpy.linspace(start,stop,numbers)
       - example
       - numpy.linspace(0,10,num=4)
       output
       - array([ 0., 3.33333333, 6.66666667, 10.])
- full
    - syntax
    - numpy.full((size),number)
- empty
    - Its initial content is random and depends on the state of the memory.
    - syntax
    - np.empty((start,stop))
    
- zeros
    - to quickly create and populate an array.
    - syntax
    - np.zeros((x,y))
- ones
    - to quickly create and populate an array.
    - syntax
    - np.ones((x,y))

In [57]:
import numpy as np
print("  arange method  \n")
arange1=np.arange(0,11,1)
arange2=np.arange(0,11,2).reshape(3,2)
print(arange1)
print(arange2)
print("\n  random.randint   ")

rand1=np.random.randint(0,2,size=(2,3))
print("\n",rand1)

print("\n    linspace   \n")
linspace=np.linspace(0,10,4)
print(linspace)

linspace1=np.linspace(0,10,5)
print(linspace1)

print("\n  full   \n")
full=np.full((2,2), 3)
print(full)

full=np.full((4,4), [3,5,4,1])
print("\n",full)

print("\n empty   \n")
e=np.empty((2,4))
print(e)

ones=np.ones((2,3))
print("\n",ones)

zeros=np.zeros((2,3))
print("\n",zeros)

  arange method  

[ 0  1  2  3  4  5  6  7  8  9 10]
[[ 0  2]
 [ 4  6]
 [ 8 10]]

  random.randint   

 [[1 1 1]
 [1 1 0]]

    linspace   

[ 0.          3.33333333  6.66666667 10.        ]
[ 0.   2.5  5.   7.5 10. ]

  full   

[[3 3]
 [3 3]]

 [[3 5 4 1]
 [3 5 4 1]
 [3 5 4 1]
 [3 5 4 1]]

 empty   

[[0.00000000e+000 0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.74303020e-321 2.14321575e-312 1.24611470e-306]]

 [[1. 1. 1.]
 [1. 1. 1.]]

 [[0. 0. 0.]
 [0. 0. 0.]]


In [50]:
#  creating different dimensions arrays using pandas

import numpy as np
d1=np.random.randint(0,10,size=6)   # 1D array
print("1D array is \n",d1)
d2=np.random.randint(0,10,size=(2,5))   # 2D array
print("\n2D array is \n",d2) 
d3=np.random.randint(1,10,size=(2,2,2)) # 3D
print("\n3D array is \n",d3)

1D array is 
 [9 5 0 6 4 9]

2D array is 
 [[6 9 1 2 1]
 [4 4 8 8 3]]

3D array is 
 [[[7 1]
  [1 4]]

 [[3 3]
  [5 4]]]


In [23]:
# Properties of an array
d3=np.random.randint(1,10,size=(2,2,2)) # 3D
print("\n3D array is \n",d3)
print("\nsize ", d3.size)
print("dtype ", d3.dtype)
print("dimention ", d3.ndim)
print("itemsize ", d3.itemsize,"bytes")
print("nbytes ",d3.nbytes)


3D array is 
 [[[4 5]
  [3 4]]

 [[5 1]
  [1 7]]]

size  8
dtype  int32
dimention  3
itemsize  4 bytes
nbytes  32


- we can use square brackets to access individual array elements
- Values can also be modified using any of the index notation:
- Array Indexing

    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    0   1  2  3  4  5  6  7  8  9     indexing from forward (positive)
    -10 -9 -8 -7 -6 -5 -4 -3 -2 -1     indexing from back word (negative)
- we can also change data based index
    

In [37]:
# Accessing single elements from 1D array

x=[i for i in range(0,10)]
print(x)
print("Staring element ",x[0]) 

print("3rd element is ",x[2])

print("2nd element from last ",x[-2])

print("last element ",x[-1])
x[1]=12
print(x[1])

x[-3]=30
print(x[-3])

print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Staring element  0
3rd element is  2
2nd element from last  8
last element  9
12
30
[0, 12, 2, 3, 4, 5, 6, 30, 8, 9]


#### Accessing single elements from 2D array
- we can use square brackets to access individual array elements
- In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

example :
- variable[row_index, column_index]
    -  when output was printed it will print starting_index to ending_index-1 elements
- variable[row_index][column_index]

idenxing is done as follows
      
   -3         -2          -1 <br>
    0         1          2  <br>
 [[9, 5, 7],[5, 4, 6],[8, 1, 7]] <br>
   0  1  2   0  1  2   0  1  2   <br>
  -3 -2  -1  -3 -2 -1  -1 -2 -3  <br>
  
  
  
  

In [47]:
import numpy as np

d2=np.random.randint(0,10,size=(3,3))
print(d2)
print(d2[0,2])
print(d2[2,1])
print(d2[2])


[[6 2 9]
 [8 8 6]
 [2 7 1]]
9
7
[2 7 1]


In [48]:

print(d2[-1][-1])
print(d2[-2])
print(d2[-3,-1])

1
[8 8 6]
9


In [50]:
# Modyfing values
d2[0,2]=123
d2[-1,-3]=321

print(d2)

[[  6   2 123]
 [  8   8   6]
 [321   7   1]]


#### Array Slicing
-  we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon : character
- x[start:stop:step]
    - start means staring index
    - stop means ending index
    - step means nothing but increment for start
    - basically step will be 1 default
- If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1


In [3]:
# 1D array
import numpy as np
x=np.arange(10)

print(x[:-1])
print(x[:5])
print(x[2:])
print(x[-1:4])
print(x[-6:-2])
print(x[2:6])
x[:]


[0 1 2 3 4 5 6 7 8]
[0 1 2 3 4]
[2 3 4 5 6 7 8 9]
[]
[4 5 6 7]
[2 3 4 5]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [7]:
print(x)
x[0::2] 

[0 1 2 3 4 5 6 7 8 9]


array([0, 2, 4, 6, 8])

- A potentially confusing case is when the step value is negative. In this case, the defaults for start and stop are swapped. This becomes a convenient way to reverse an array:

In [11]:
a=[1,2,3,4,5,6,7,8,9]
print(a[::-1])
print(a[7::-2])

print(a[::-2])

[9, 8, 7, 6, 5, 4, 3, 2, 1]
[8, 6, 4, 2]
[9, 7, 5, 3, 1]


### Multi-dimensional subarrays
- Multi-dimensional slices work in the same way, with multiple slices separated by commas.

In [12]:
import numpy as np
d2=np.random.randint(1,10,size=(2,3,2))

d2

array([[[2, 9],
        [9, 1],
        [1, 3]],

       [[5, 3],
        [5, 4],
        [2, 1]]])

In [16]:
d2[::-1]

array([[[3, 4],
        [4, 3],
        [4, 2]],

       [[2, 1],
        [1, 1],
        [2, 5]]])

In [19]:
d2[::1]

array([[[2, 1],
        [1, 1],
        [2, 5]],

       [[3, 4],
        [4, 3],
        [4, 2]]])

In [20]:
d2[::1,::2]

array([[[2, 1],
        [2, 5]],

       [[3, 4],
        [4, 2]]])

In [25]:
d2[::1,::-1,::-1]

array([[[5, 2],
        [1, 1],
        [1, 2]],

       [[2, 4],
        [3, 4],
        [4, 3]]])


### Accessing array rows and columns

- One commonly needed routine is accessing of single rows or columns of an array. This can be done by combining indexing and slicing, using an empty slice marked by a single colon (:):


In [26]:
d2[1][1]

array([4, 3])

In [27]:
d2[1,1]

array([4, 3])

In [30]:
d2[0]

array([[2, 1],
       [1, 1],
       [2, 5]])


### Reshaping of Arrays

- Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a $3 \times 3$ grid, you can do the following:
